export const CHANGE_SEARCHFIELD = 'CHANGE_SEARCHFIELD';

export const REQUEST_PRODUCTS_PENDING = 'REQUEST_PRODUCTS_PENDING';
export const REQUEST_PRODUCTS_SUCCESS = 'REQUEST_PRODUCTS_SUCCESS';
export const REQUEST_PRODUCTS_FAIL = 'REQUEST_PRODUCTS_FAIL';